bp_bonobo_friend:
    resource: "@BPBonoboBundle/Controller/FriendController.php"
    type:     annotation

bp_bonobo_user:
    resource: "@BPBonoboBundle/Controller/UserController.php"
    type:     annotation

bp_bonobo:
    resource: "@BPBonoboBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



